wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704725387.616771
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.11.0
      5: 0.16.1
      6: 4.35.2
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
