defaults: 
  - architecture: resnet

training:
  max_epochs: 5

data:
  raw_dir: data/raw
  processed_dir: data/processed
  batch_size: 1000
  num_workers: 0
  val_size: 10000
  seed: 42
  train:
    transformations:
      rotation:
        degrees: 5
        
  test:
    transformations:
      
  val:
    transformations:
