defaults:
  - architecture: resnet
  - sweep: sweep_config

training:
  max_epochs: 5

data:
  channels: 3 # Amount fo channels for create - default is 3 since many TIMM models requires this
  raw_dir: data/raw
  processed_dir: data/processed
  batch_size: 1000
  num_workers: 7
  val_size: 10000
  seed: 42
  train:
    transformations:
      rotation:
        degrees: 5
      grayscale_to_rgb: {}

  test:
    transformations:

  val:
    transformations:
